<a href="https://colab.research.google.com/github/dkpark10/Python-Practice/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

l=list(range(2,19,2))
a=np.array(l)
print("current array: {} ".format(a))

a=np.append(a,234) #array에 값 추가
print("current array: {} ".format(a))

print('printing each element')

for i in a: 
  print(i, end=" ")
print() 
for i,e in enumerate(a):
  print('index: {}, value: {}'.format(i,e))
  

current array: [ 2  4  6  8 10 12 14 16 18] 
current array: [  2   4   6   8  10  12  14  16  18 234] 
printing each element
2 4 6 8 10 12 14 16 18 234 
index: 0, value: 2
index: 1, value: 4
index: 2, value: 6
index: 3, value: 8
index: 4, value: 10
index: 5, value: 12
index: 6, value: 14
index: 7, value: 16
index: 8, value: 18
index: 9, value: 234


# numpy 수학연산

In [8]:
b=np.array(l)
print(b)
print('max = {}'.format(np.max(b)))
print('average= {}'.format(np.average(b)))
print('index of max ={}'.format(np.argmax(b)))
print('min = {}'.format(np.min(b)))
print('index of min ={}'.format(np.argmin(b)))

[ 2  4  6  8 10 12 14 16 18]
max = 18
average= 10.0
index of max =8
min = 2
index of min =0


# numpy Type

In [9]:
print('type of a {}, type of a[0]{}'.format(type(a),type(a[0]))) # type of a <class 'numpy.ndarray'>, type of a[0]<class 'numpy.int64'>

type of a <class 'numpy.ndarray'>, type of a[0]<class 'numpy.int64'>


In [11]:
c= np.random.rand(3,3) # 3*3 랜덤어레이 
print(c)
print(type(c))

[[0.39048844 0.75756179 0.66413789]
 [0.22976456 0.91701989 0.29967064]
 [0.57927597 0.37654416 0.78205474]]
<class 'numpy.ndarray'>


In [0]:
print('shape of a: {}'.format(a.shape)) # 1차원
print('shape of b: {}'.format(b.shape))
print('shape of c: {}'.format(c.shape)) # 2차원

shape of a: (3,)
shape of b: (5,)
shape of c: (3, 3)


In [0]:
import numpy as np
from IPython.display import display

aa=np.array([1,2,3]) # 랭크 1 배열을 만든다 
print(type(aa),aa.shape,aa[0],aa[1],aa[2])
aa[0]=5              # 값을 대입
display(aa)

<class 'numpy.ndarray'> (3,) 1 2 3


array([5, 2, 3])

In [12]:
l1= list(range(3))
l2= list(range(4,7))

bb= np.array([l1,l2]) # 랭크 2 배열 
display(bb)
print(bb.shape)       # [2][3] 배열
print(bb[0][0],bb[0][1],bb[1][0])

array([[0, 1, 2],
       [4, 5, 6]])

(2, 3)
0 1 4


In [19]:
aa=np.zeros((1,1)) # 0으로 초기화
display(aa) 

array([[0.]])

In [16]:
b=np.ones((2,2)) # 1로 설정된 ndarray를 생성 
display(b)

array([[1., 1.],
       [1., 1.]])

In [20]:
c=np.full((2,2),7) # 상수 7로 설정된 ndarray를 생성한다. 2*2 배열
display(c)

array([[7, 7],
       [7, 7]])

In [28]:
np.ones((2,2)) *12 # 모든 요소에 12을 곱함 


array([[12., 12.],
       [12., 12.]])

In [27]:
d=np.eye(7) # 단위 행렬 대각선에 값
print(d)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [24]:
e= np.random.random((2,2)) # 0-1 사이 랜덤으로 2*2 배열생성
display(e)

array([[0.21392602, 0.3466814 ],
       [0.40712177, 0.9037656 ]])

In [29]:
f= np.random.randn(4,4) # 표준 정규분포를 따르는 무작위값 배열 생ㅅㅇ 
display(f)

array([[ 0.20862022, -0.57984485,  0.51713798, -0.77832702],
       [ 1.22206634, -1.42546373, -0.80183285, -0.66733522],
       [ 1.11147494, -0.24475851, -0.1615211 ,  0.8131974 ],
       [ 2.53343493, -0.45304065, -0.11451207,  2.49146859]])

In [0]:
g= np.random.normal(size=(2,2))
display(g)
np.random.normal?

array([[ 0.1047425 ,  2.04604376],
       [ 0.01474402, -0.87940932]])

In [30]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2, 1:3] # 얕은복사 b 바꾸면 a 도 바뀜 0~1인덱스에서 1~2 뽑기
display(b)

array([[2, 3],
       [6, 7]])

In [33]:
print(a[0][1])
b[0,0]=11
print(a[0][1])

11
11


In [0]:
# 단층 퍼셉트론으로 AND 게이트 구현

def AND(x1, x2):
  x=np.array([x1,x2])
  w=np.array([0.5,0.5])
  b=-0.7
  tmp=np.sum(w*x)+b
  print(tmp)

  if(tmp<=0):
    return 0
  else:
    return 1 
  
if __name__ == "__main__":
  for xs in [(0,0),(0,1),(1,0),(1,1)]:
    y=AND(xs[0],xs[1])
    print((str(xs)+" --->"+str(y)))

(0, 0) --->0
(0, 1) --->0
(1, 0) --->0
(1, 1) --->1


In [0]:
# 단층 퍼셉트론으로 NAND 게이트 구현

def NAND(x1, x2):
  x=np.array([x1,x2])
  w=np.array([-0.5,-0.5])
  b=0.7
  tmp=np.sum(w*x)+b
  print(tmp)
  
  if(tmp<=0):
    return 0
  else:
    return 1 
  
if __name__ == "__main__":
  for xs in [(0,0),(0,1),(1,0),(1,1)]:
    y=NAND(xs[0],xs[1])
    print((str(xs)+" --->"+str(y)))

0.7
(0, 0) --->1
0.19999999999999996
(0, 1) --->1
0.19999999999999996
(1, 0) --->1
-0.30000000000000004
(1, 1) --->0


In [0]:
# 단층 퍼셉트론으로 OR 게이트 구현

def OR(x1, x2):
  x=np.array([x1,x2])
  w=np.array([0.5,0.5])
  b=-0.3
  tmp=np.sum(w*x)+b
  print(tmp)
  
  if(tmp<=0):
    return 0
  else:
    return 1 
  
if __name__ == "__main__":
  for xs in [(0,0),(0,1),(1,0),(1,1)]:
    y=OR(xs[0],xs[1])
    print((str(xs)+" --->"+str(y)))


-0.3
(0, 0) --->0
0.2
(0, 1) --->1
0.2
(1, 0) --->1
0.7
(1, 1) --->1


In [0]:
test1=np.array([[0,0],[0,1]])
display(test1)

test2=np.array([0.5,0.5])

result= np.sum(test1*test2)
print(result)


array([[0, 0],
       [0, 1]])

0.5
<class 'list'>


In [0]:
import numpy as np

l= list(range(1,8+1))
nn= np.array(l)
nn=nn.reshape(4,2) # 배열 모양 재정렬

print(nn,'\n')
print(nn[1][1],'\n') # 1,1 인덱스 반환

three = np.arange(9).reshape(3,3)
print(three)


[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

4 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
